/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primary (Forest Emerald)
        primary: '#003629',
        'primary-hover': '#004d3b',
        'primary-container': '#1b4d3e',
        'primary-fixed': '#baeed9',
        'primary-fixed-dim': '#9ed1bd',
        'on-primary': '#ffffff',
        'on-primary-container': '#8abda9',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#1d4f40',

        // Secondary (Amber / Warm Terracotta)
        secondary: '#7e5700',
        'secondary-container': '#fdbe50',
        'secondary-fixed': '#ffdead',
        'secondary-fixed-dim': '#fabc4d',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#714d00',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#604100',

        // Tertiary (Teal / Mint)
        tertiary: '#003625',
        'tertiary-container': '#004f38',
        'tertiary-fixed': '#abf1d0',
        'tertiary-fixed-dim': '#90d5b5',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#7cc0a1',
        'on-tertiary-fixed': '#002115',
        'on-tertiary-fixed-variant': '#00513a',

        // Surface & Background
        background: '#f9f9ff',
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf2',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#d8e3fb',
        'surface-tint': '#376757',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fb',

        // Text & Outlines
        'on-background': '#111c2d',
        'on-surface': '#111c2d',
        'on-surface-variant': '#404945',
        outline: '#707974',
        'outline-variant': '#c0c9c3',

        // Inverse
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'inverse-primary': '#9ed1bd',

        // Status / Error
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        success: '#004530',
        warning: '#7e5700',
        info: '#005f44',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.125rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4rem',
        'gutter-desktop': '1.5rem',
        'gutter-mobile': '1rem',
        'margin-desktop': '3rem',
        'margin-tablet': '2rem',
        'margin-mobile': '1rem',
        'container-max-width': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        heading: ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'numeric-metric': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'numeric-metric': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        sm: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
        DEFAULT: '0 1px 8px rgba(0,0,0,0.04)',
        md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
        lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
        xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
      },
    },
  },
  plugins: [],
};
