"""create foods and food_portions tables

Revision ID: 86b782fd2783
Revises: '9d6637193e2a'
Create Date: 2026-09-06 19:19:50.290573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b782fd2783'
down_revision: Union[str, None] = '9d6637193e2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ifct_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('alternate_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('serving_size_name', sa.String(length=100), nullable=False),
    sa.Column('serving_size_g', sa.Float(), nullable=False),
    sa.Column('calories', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_category'), 'foods', ['category'], unique=False)
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_ifct_code'), 'foods', ['ifct_code'], unique=True)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_index(op.f('ix_foods_region'), 'foods', ['region'], unique=False)
    op.create_table('food_portions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('portion_name', sa.String(length=100), nullable=False),
    sa.Column('gram_weight', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_food_portions_food_id'), 'food_portions', ['food_id'], unique=False)
    op.create_index(op.f('ix_food_portions_id'), 'food_portions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_portions_id'), table_name='food_portions')
    op.drop_index(op.f('ix_food_portions_food_id'), table_name='food_portions')
    op.drop_table('food_portions')
    op.drop_index(op.f('ix_foods_region'), table_name='foods')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_ifct_code'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_category'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
